In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
edu=pd.read_csv(r"C:\Users\diksh\Downloads\xAPI-Edu-Data.csv",index_col=None,header=0)
edu.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [3]:
edu.shape


(480, 17)

In [4]:
edu.describe(include='all')

gender NationalITy PlaceofBirth       StageID GradeID SectionID Topic  \
count     480         480          480           480     480       480   480   
unique      2          14           14             3      10         3    12   
top         M          KW       KuwaIT  MiddleSchool    G-02         A    IT   
freq      305         179          180           248     147       283    95   
mean      NaN         NaN          NaN           NaN     NaN       NaN   NaN   
std       NaN         NaN          NaN           NaN     NaN       NaN   NaN   
min       NaN         NaN          NaN           NaN     NaN       NaN   NaN   
25%       NaN         NaN          NaN           NaN     NaN       NaN   NaN   
50%       NaN         NaN          NaN           NaN     NaN       NaN   NaN   
75%       NaN         NaN          NaN           NaN     NaN       NaN   NaN   
max       NaN         NaN          NaN           NaN     NaN       NaN   NaN   

       Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
count       480      480   480.000000        480.000000         480.000000   
unique        2        2          NaN               NaN                NaN   
top           F   Father          NaN               NaN                NaN   
freq        245      283          NaN               NaN                NaN   
mean        NaN      NaN    46.775000         54.797917          37.918750   
std         NaN      NaN    30.779223         33.080007          26.611244   
min         NaN      NaN     0.000000          0.000000           0.000000   
25%         NaN      NaN    15.750000         20.000000          14.000000   
50%         NaN      NaN    50.000000         65.000000          33.000000   
75%         NaN      NaN    75.000000         84.000000          58.000000   
max         NaN      NaN   100.000000         99.000000          98.000000   

        Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
count   480.000000                   480                      480   
unique         NaN                     2                        2   
top            NaN                   Yes                     Good   
freq           NaN                   270                      292   
mean     43.283333                   NaN                      NaN   
std      27.637735                   NaN                      NaN   
min       1.000000                   NaN                      NaN   
25%      20.000000                   NaN                      NaN   
50%      39.000000                   NaN                      NaN   
75%      70.000000                   NaN                      NaN   
max      99.000000                   NaN                      NaN   

       StudentAbsenceDays Class  
count                 480   480  
unique                  2     3  
top               Under-7     M  
freq                  289   211  
mean                  NaN   NaN  
std                   NaN   NaN  
min                   NaN   NaN  
25%                   NaN   NaN  
50%                   NaN   NaN  
75%                   NaN   NaN  
max                   NaN   NaN

## Pre processing

In [5]:
#create a copy of the dataframe
edu1=pd.DataFrame.copy(edu)

In [6]:
edu1.columns

Index(['gender', 'NationalITy', 'PlaceofBirth', 'StageID', 'GradeID',
       'SectionID', 'Topic', 'Semester', 'Relation', 'raisedhands',
       'VisITedResources', 'AnnouncementsView', 'Discussion',
       'ParentAnsweringSurvey', 'ParentschoolSatisfaction',
       'StudentAbsenceDays', 'Class'],
      dtype='object')

In [7]:
edu1.isnull().sum()

gender                      0
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 0
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [8]:
# insight: there are no missing values in the data

In [9]:
edu1.dtypes

gender                      object
NationalITy                 object
PlaceofBirth                object
StageID                     object
GradeID                     object
SectionID                   object
Topic                       object
Semester                    object
Relation                    object
raisedhands                  int64
VisITedResources             int64
AnnouncementsView            int64
Discussion                   int64
ParentAnsweringSurvey       object
ParentschoolSatisfaction    object
StudentAbsenceDays          object
Class                       object
dtype: object

In [10]:
for i in edu1.columns:
    print({i:edu1[i].unique()})

{'gender': array(['M', 'F'], dtype=object)}
{'NationalITy': array(['KW', 'lebanon', 'Egypt', 'SaudiArabia', 'USA', 'Jordan',
       'venzuela', 'Iran', 'Tunis', 'Morocco', 'Syria', 'Palestine',
       'Iraq', 'Lybia'], dtype=object)}
{'PlaceofBirth': array(['KuwaIT', 'lebanon', 'Egypt', 'SaudiArabia', 'USA', 'Jordan',
       'venzuela', 'Iran', 'Tunis', 'Morocco', 'Syria', 'Iraq',
       'Palestine', 'Lybia'], dtype=object)}
{'StageID': array(['lowerlevel', 'MiddleSchool', 'HighSchool'], dtype=object)}
{'GradeID': array(['G-04', 'G-07', 'G-08', 'G-06', 'G-05', 'G-09', 'G-12', 'G-11',
       'G-10', 'G-02'], dtype=object)}
{'SectionID': array(['A', 'B', 'C'], dtype=object)}
{'Topic': array(['IT', 'Math', 'Arabic', 'Science', 'English', 'Quran', 'Spanish',
       'French', 'History', 'Biology', 'Chemistry', 'Geology'],
      dtype=object)}
{'Semester': array(['F', 'S'], dtype=object)}
{'Relation': array(['Father', 'Mum'], dtype=object)}
{'raisedhands': array([ 15,  20,  10,  30,  40,  42

In [11]:
edu1.duplicated().sum()


2

## Converting catorgircal to Numerical values 

In [12]:
# to get the list of variable for catigorcal
colname=[]
for x in edu1.columns:
    if edu1[x].dtype=='object':
        colname.append(x)
colname

['gender',
 'NationalITy',
 'PlaceofBirth',
 'StageID',
 'GradeID',
 'SectionID',
 'Topic',
 'Semester',
 'Relation',
 'ParentAnsweringSurvey',
 'ParentschoolSatisfaction',
 'StudentAbsenceDays',
 'Class']

In [13]:
#applying lable encoder for pre processing
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    edu1[x]=le.fit_transform(edu1[x])
    

In [14]:
edu1.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  raisedhands  VisITedResources  AnnouncementsView  \
0         0         0           15                16                  2   
1         0         0           20                20                  3   
2         0         0           10                 7                  0   
3         0         0           30                25                  5   
4         0         0           40                50                 12   

   Discussion  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0          20                      1                         1   
1          25                      1                         1   
2          30                      0                         0   
3          35                      0                         0   
4          50                      0                         0   

   StudentAbsenceDays  Class  
0                   1      2  
1                   1      2  
2                   0      1  
3                   0      1  
4                   0      2

In [15]:
#creating the x and y values 
X=edu1.values[:,0:-1] #-->0 to -2 which is equivaltent to 0 to 12 which will take fro 0 to 11 the another way of writing this is 0:-1
Y=edu1.values[:,-1]

In [16]:
Y.shape

(480,)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
#x=scaler.fit_transform(X)
print(X)

[[ 0.7574764  -0.1402013  -0.15155299 ...  0.8819171   0.80239368
   0.81295735]
 [ 0.7574764  -0.1402013  -0.15155299 ...  0.8819171   0.80239368
   0.81295735]
 [ 0.7574764  -0.1402013  -0.15155299 ... -1.13389342 -1.24627103
  -1.23007683]
 ...
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
   0.81295735]
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
  -1.23007683]
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
  -1.23007683]]


## Training Phase

In [18]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [19]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(384, 16)
(384,)
(96, 16)
(96,)


In [20]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression()
#train the model object
classifier.fit(X_train,Y_train)# fit function is used to train the model

Y_pred=classifier.predict(X_test)
print(Y_pred)


#print intercept and coeeficients
print(classifier.intercept_) #to get dependent values 
print(classifier.coef_)

[0 2 2 1 2 0 0 0 2 1 2 2 2 2 2 2 1 0 2 2 1 2 1 2 2 1 0 0 2 0 2 0 1 2 2 1 2
 2 1 0 2 1 2 1 2 2 0 2 2 0 2 1 2 2 2 0 0 1 2 0 0 1 0 2 2 2 2 0 1 0 2 1 2 2
 2 2 1 1 2 0 1 0 1 1 2 0 1 0 0 2 0 1 2 2 0 0]
[-0.18937794 -1.40606545  1.59544339]
[[-0.23374106 -0.20091011  0.29639902 -0.26949596 -0.49056957  0.08291724
  -0.14332525  0.02887985  0.42978042  0.81158964  0.4829869   0.32158494
   0.40410823  0.346182    0.23697169  1.1468254 ]
 [ 0.27651169  0.34408589 -0.35342731  0.44861223  0.55200523  0.03544186
   0.02445637  0.06347401 -0.23572834 -0.82675725 -0.64370987 -0.65644349
  -0.35032309 -0.40528263 -0.1852358  -1.27372642]
 [-0.04277063 -0.14317578  0.0570283  -0.17911627 -0.06143567 -0.1183591
   0.11886888 -0.09235386 -0.19405208  0.01516761  0.16072297  0.33485855
  -0.05378514  0.05910063 -0.05173589  0.12690102]]


In [21]:
classifier.predict_proba(X_test)

array([[5.07175032e-01, 6.49662405e-03, 4.86328344e-01],
       [8.89667991e-02, 1.68878621e-01, 7.42154580e-01],
       [1.55896251e-02, 1.34927588e-01, 8.49482787e-01],
       [7.69037039e-03, 7.19663386e-01, 2.72646243e-01],
       [4.43586690e-01, 9.83478373e-03, 5.46578526e-01],
       [9.01505895e-01, 1.04888248e-05, 9.84836165e-02],
       [6.81123326e-01, 1.32005631e-03, 3.17556618e-01],
       [5.88810429e-01, 2.12164682e-03, 4.09067924e-01],
       [9.24404687e-03, 3.25392031e-01, 6.65363922e-01],
       [1.25344127e-04, 9.54302903e-01, 4.55717526e-02],
       [4.76619782e-01, 5.88564642e-04, 5.22791653e-01],
       [2.07704140e-02, 4.08035608e-01, 5.71193978e-01],
       [4.44061564e-01, 9.18550905e-03, 5.46752927e-01],
       [1.43232262e-01, 1.15606743e-01, 7.41160996e-01],
       [1.97418899e-01, 7.29926689e-03, 7.95281834e-01],
       [4.24691562e-01, 2.58128144e-03, 5.72727156e-01],
       [1.80194859e-04, 9.59880787e-01, 3.99390180e-02],
       [7.30051480e-01, 3.27499

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [10  3 37]]
Classification report: 
              precision    recall  f1-score   support

           0       0.63      0.74      0.68        23
           1       0.87      0.87      0.87        23
           2       0.80      0.74      0.77        50

    accuracy                           0.77        96
   macro avg       0.77      0.78      0.77        96
weighted avg       0.78      0.77      0.77        96

Accuracy of the model:  0.7708333333333334


# SGD

In [23]:
from sklearn.linear_model import SGDClassifier
#create a model
sgdclassifier=SGDClassifier(loss="log",random_state=10,learning_rate="constant",
                         eta0=0.00001,max_iter=1000, shuffle=True,
                        early_stopping=True,n_iter_no_change=3)
#fitting training data to the model
sgdclassifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [10  3 37]]
Classification report: 
              precision    recall  f1-score   support

           0       0.63      0.74      0.68        23
           1       0.87      0.87      0.87        23
           2       0.80      0.74      0.77        50

    accuracy                           0.77        96
   macro avg       0.77      0.78      0.77        96
weighted avg       0.78      0.77      0.77        96

Accuracy of the model:  0.7708333333333334


In [25]:
sgdclassifier.n_iter_

4

In [26]:
sgdclassifier.t_

1537.0

# Cross validation

In [27]:
#Using cross validation

classifier=LogisticRegression()# it will tell K-fold will tell that logistic regression should be done only this line will change in all algorthim

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10,random_state=10,shuffle=True)#n_splits means k =10
#print(kfold_cv)

from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,
                                                 y=Y_train, cv=kfold_cv)
print(kfold_cv_result)
#finding the mean
print(kfold_cv_result.mean())

[0.82051282 0.66666667 0.76923077 0.71794872 0.71052632 0.71052632
 0.71052632 0.76315789 0.68421053 0.84210526]
0.7395411605937923


In [28]:
#model tuning for more than 3% difference then we can go for cross validated model and we can use this as model tuning 

for train_value, test_value in kfold_cv.split(X_train):
    classifier.fit(X_train[train_value], Y_train[train_value]).predict(X_train[test_value])

    
Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [13  3 34]]
Classification report: 
              precision    recall  f1-score   support

           0       0.57      0.74      0.64        23
           1       0.87      0.87      0.87        23
           2       0.79      0.68      0.73        50

    accuracy                           0.74        96
   macro avg       0.74      0.76      0.75        96
weighted avg       0.76      0.74      0.74        96

Accuracy of the model:  0.7395833333333334


In [30]:
## we can see here that base model was better than k-fold after tuning 

In [31]:
#using straified Kfold
classifier=LogisticRegression()# it will tell K-fold will tell that logistic regression should be done only this line will change in all algorthim

#performing Stratifiedkfold_cross_validation
from sklearn.model_selection import StratifiedKFold
kfold_cv=StratifiedKFold(n_splits=10,random_state=10,shuffle=True)#n_splits means k =10
#print(Stratifiedkfold_cv)

from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,
                                                 y=Y_train, cv=kfold_cv)
print(kfold_cv_result)
#finding the mean
print(kfold_cv_result.mean())

[0.82051282 0.66666667 0.84615385 0.76923077 0.55263158 0.78947368
 0.81578947 0.60526316 0.76315789 0.60526316]
0.7234143049932524


In [32]:
for train_value, test_value in kfold_cv.split(X_train,Y_train):
    classifier.fit(X_train[train_value], Y_train[train_value]).predict(X_train[test_value])

    
Y_pred=classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [11  2 37]]
Classification report: 
              precision    recall  f1-score   support

           0       0.61      0.74      0.67        23
           1       0.91      0.87      0.89        23
           2       0.80      0.74      0.77        50

    accuracy                           0.77        96
   macro avg       0.77      0.78      0.78        96
weighted avg       0.78      0.77      0.77        96

Accuracy of the model:  0.7708333333333334


In [34]:
# we can see here that there was no much differnce between the base model and straified k-fold after tuning 

# SelectKBest function

In [35]:
#Recreating the x and y values 
X=edu1.values[:,:-1] 
Y=edu1.values[:,-1]

In [36]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


test = SelectKBest(score_func=chi2, k=8)# here it tells us out of 15b variable in the list it will compare every x with  y and give 8 best values 
fit1 = test.fit(X, Y)

colname=edu1.columns

print(fit1.scores_)
print(list(zip(colname,fit1.get_support())))
X_new = fit1.transform(X)

[1.21501902e+01 6.95502702e+00 9.75721839e+00 1.36112198e+00
 7.18665588e+00 5.15850555e-01 1.39038817e+01 3.99229972e+00
 4.79717673e+01 4.12455120e+03 4.70083310e+03 2.61890570e+03
 8.09349399e+02 4.17220341e+01 2.68172275e+01 8.96127511e+01]
[('gender', False), ('NationalITy', False), ('PlaceofBirth', False), ('StageID', False), ('GradeID', False), ('SectionID', False), ('Topic', False), ('Semester', False), ('Relation', True), ('raisedhands', True), ('VisITedResources', True), ('AnnouncementsView', True), ('Discussion', True), ('ParentAnsweringSurvey', True), ('ParentschoolSatisfaction', True), ('StudentAbsenceDays', True)]


In [37]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_new)
X=scaler.transform(X_new)

In [38]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [39]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression()
#train the model object
classifier.fit(X_train,Y_train)# fit function is used to train the model

Y_pred=classifier.predict(X_test)
print(Y_pred)


#print intercept and coeeficients
print(classifier.intercept_) #to get dependent values 
print(classifier.coef_)

[0 2 2 1 2 0 0 0 2 1 2 1 2 2 2 2 1 0 2 2 1 2 1 2 2 1 0 0 2 0 2 0 1 2 2 1 2
 2 1 0 2 1 2 1 2 0 0 2 2 2 2 1 0 2 2 2 0 1 2 0 0 1 0 2 2 2 2 2 1 0 2 1 2 2
 2 2 2 1 2 0 1 0 1 1 2 0 1 0 0 2 0 1 2 2 0 2]
[-0.14482944 -1.41517937  1.5600088 ]
[[ 0.4677957   0.76186719  0.52833565  0.23131647  0.33975349  0.33484478
   0.21617972  1.19728301]
 [-0.24150777 -0.84991361 -0.65801443 -0.54007497 -0.36922082 -0.40229439
  -0.18997168 -1.29585327]
 [-0.22628793  0.08804642  0.12967878  0.3087585   0.02946733  0.06744961
  -0.02620804  0.09857026]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [ 8  3 39]]
Classification report: 
              precision    recall  f1-score   support

           0       0.68      0.74      0.71        23
           1       0.87      0.87      0.87        23
           2       0.81      0.78      0.80        50

    accuracy                           0.79        96
   macro avg       0.79      0.80      0.79        96
weighted avg       0.79      0.79      0.79        96

Accuracy of the model:  0.7916666666666666


In [41]:
#insight : Select K best works well when compared to k fold straified k fold and base  model 

# Variance Threshold

In [42]:
#Recreating the x and y values 
X=edu1.values[:,:-1] 
Y=edu1.values[:,-1]

In [43]:
from sklearn.feature_selection import VarianceThreshold
vt = VarianceThreshold(0.2)
fit1 = vt.fit(X, Y)
print(fit1.variances_)

features = fit1.transform(X)
print(features.shape[1])
print(list(zip(edu1.columns,fit1.get_support())))

[2.31662326e-01 6.08456597e+00 6.89374566e+00 3.63732639e-01
 6.05996094e+00 3.74266493e-01 1.14572526e+01 2.49891493e-01
 2.41974826e-01 9.45386875e+02 1.09200708e+03 7.06682982e+02
 7.62253056e+02 2.46093750e-01 2.38263889e-01 2.39578993e-01]
16
[('gender', True), ('NationalITy', True), ('PlaceofBirth', True), ('StageID', True), ('GradeID', True), ('SectionID', True), ('Topic', True), ('Semester', True), ('Relation', True), ('raisedhands', True), ('VisITedResources', True), ('AnnouncementsView', True), ('Discussion', True), ('ParentAnsweringSurvey', True), ('ParentschoolSatisfaction', True), ('StudentAbsenceDays', True)]


In [44]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_new)
X=scaler.transform(X_new)

In [45]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [46]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression()
#train the model object
classifier.fit(X_train,Y_train)# fit function is used to train the model

Y_pred=classifier.predict(X_test)
print(Y_pred)


#print intercept and coeeficients
print(classifier.intercept_) #to get dependent values 
print(classifier.coef_)#

[0 2 2 1 2 0 0 0 2 1 2 1 2 2 2 2 1 0 2 2 1 2 1 2 2 1 0 0 2 0 2 0 1 2 2 1 2
 2 1 0 2 1 2 1 2 0 0 2 2 2 2 1 0 2 2 2 0 1 2 0 0 1 0 2 2 2 2 2 1 0 2 1 2 2
 2 2 2 1 2 0 1 0 1 1 2 0 1 0 0 2 0 1 2 2 0 2]
[-0.14482944 -1.41517937  1.5600088 ]
[[ 0.4677957   0.76186719  0.52833565  0.23131647  0.33975349  0.33484478
   0.21617972  1.19728301]
 [-0.24150777 -0.84991361 -0.65801443 -0.54007497 -0.36922082 -0.40229439
  -0.18997168 -1.29585327]
 [-0.22628793  0.08804642  0.12967878  0.3087585   0.02946733  0.06744961
  -0.02620804  0.09857026]]


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[17  0  6]
 [ 0 20  3]
 [ 8  3 39]]
Classification report: 
              precision    recall  f1-score   support

           0       0.68      0.74      0.71        23
           1       0.87      0.87      0.87        23
           2       0.81      0.78      0.80        50

    accuracy                           0.79        96
   macro avg       0.79      0.80      0.79        96
weighted avg       0.79      0.79      0.79        96

Accuracy of the model:  0.7916666666666666


In [48]:
 #variance threshold and select k best works well and gives good accuracy and recall 

# RFE Method Model

In [49]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

In [50]:
#Recreating the x and y values 
X=edu1.values[:,:-1] 
Y=edu1.values[:,-1]

In [51]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
#x=scaler.fit_transform(X)
print(X)

[[ 0.7574764  -0.1402013  -0.15155299 ...  0.8819171   0.80239368
   0.81295735]
 [ 0.7574764  -0.1402013  -0.15155299 ...  0.8819171   0.80239368
   0.81295735]
 [ 0.7574764  -0.1402013  -0.15155299 ... -1.13389342 -1.24627103
  -1.23007683]
 ...
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
   0.81295735]
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
  -1.23007683]
 [-1.32017315 -0.54560266 -0.53241913 ... -1.13389342 -1.24627103
  -1.23007683]]


In [52]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [53]:
colname=edu1.columns

In [54]:
edu1.shape

(480, 17)

In [55]:
from sklearn.feature_selection import RFE
rfe = RFE(classifier, n_features_to_select=10)
model_rfe = rfe.fit(X_train, Y_train)
print("Num Features: ",model_rfe.n_features_)
print("Selected Features: ") 
print(list(zip(colname, model_rfe.support_)))
print("Feature Ranking: ", model_rfe.ranking_) 

Num Features:  10
Selected Features: 
[('gender', True), ('NationalITy', False), ('PlaceofBirth', False), ('StageID', True), ('GradeID', True), ('SectionID', False), ('Topic', False), ('Semester', False), ('Relation', True), ('raisedhands', True), ('VisITedResources', True), ('AnnouncementsView', True), ('Discussion', True), ('ParentAnsweringSurvey', True), ('ParentschoolSatisfaction', False), ('StudentAbsenceDays', True)]
Feature Ranking:  [1 2 3 1 1 6 5 7 1 1 1 1 1 1 4 1]


In [56]:
Y_pred=model_rfe.predict(X_test)

In [57]:
print(Y_pred)

[2 2 2 1 0 0 0 0 2 1 0 2 2 2 2 0 1 0 2 0 1 2 1 2 2 1 0 0 2 0 0 0 1 2 0 1 2
 2 1 0 2 1 2 1 2 0 0 2 2 0 2 1 2 2 2 0 0 1 2 0 0 1 0 2 2 2 2 0 1 0 2 1 2 2
 2 2 2 1 0 0 1 0 1 1 2 0 2 0 0 2 0 1 2 2 0 0]


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[20  0  3]
 [ 0 19  4]
 [14  2 34]]
Classification report: 
              precision    recall  f1-score   support

           0       0.59      0.87      0.70        23
           1       0.90      0.83      0.86        23
           2       0.83      0.68      0.75        50

    accuracy                           0.76        96
   macro avg       0.77      0.79      0.77        96
weighted avg       0.79      0.76      0.76        96

Accuracy of the model:  0.7604166666666666


## SFS Method model

In [59]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
#Define Sequential Forward Selection (sfs)
sffs = SFS(LogisticRegression(),
           k_features='best',
           forward=True,
           scoring = 'accuracy',
           cv = 5)
#Use SFS to select the top features 
feature_names=edu1.columns
sffs.fit(X_train, Y_train)

#Create a dataframe for the SFS results 
df_SFFS_results = pd.DataFrame(sffs.subsets_).transpose()
df_SFFS_results

feature_idx  \
1                                                (9,)   
2                                             (9, 15)   
3                                         (9, 13, 15)   
4                                      (8, 9, 13, 15)   
5                                  (8, 9, 13, 14, 15)   
6                              (8, 9, 10, 13, 14, 15)   
7                           (4, 8, 9, 10, 13, 14, 15)   
8                        (3, 4, 8, 9, 10, 13, 14, 15)   
9                    (3, 4, 8, 9, 10, 12, 13, 14, 15)   
10                (3, 4, 7, 8, 9, 10, 12, 13, 14, 15)   
11            (3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15)   
12         (1, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15)   
13      (1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)   
14   (1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)   
15  (0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14...   
16  (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   

                                            cv_scores avg_score  \
1   [0.5714285714285714, 0.6233766233766234, 0.519...  0.596548   
2   [0.7532467532467533, 0.7012987012987013, 0.623...  0.687594   
3   [0.7402597402597403, 0.7402597402597403, 0.649...  0.713568   
4   [0.7532467532467533, 0.7792207792207793, 0.649...  0.731921   
5   [0.7402597402597403, 0.7922077922077922, 0.675...  0.747505   
6   [0.7402597402597403, 0.7792207792207793, 0.662...  0.744805   
7   [0.7532467532467533, 0.7532467532467533, 0.688...  0.742208   
8   [0.7532467532467533, 0.7402597402597403, 0.701...  0.747437   
9   [0.7402597402597403, 0.7272727272727273, 0.701...  0.742276   
10  [0.7402597402597403, 0.7402597402597403, 0.701...  0.750068   
11  [0.7662337662337663, 0.7402597402597403, 0.727...  0.755297   
12  [0.7662337662337663, 0.7662337662337663, 0.727...  0.752529   
13  [0.7662337662337663, 0.7402597402597403, 0.727...  0.747437   
14  [0.7662337662337663, 0.7142857142857143, 0.740...  0.744805   
15  [0.7662337662337663, 0.7532467532467533, 0.727...  0.734347   
16  [0.7662337662337663, 0.7792207792207793, 0.727...  0.742174   

                                        feature_names  
1                                                (9,)  
2                                             (9, 15)  
3                                         (9, 13, 15)  
4                                      (8, 9, 13, 15)  
5                                  (8, 9, 13, 14, 15)  
6                              (8, 9, 10, 13, 14, 15)  
7                           (4, 8, 9, 10, 13, 14, 15)  
8                        (3, 4, 8, 9, 10, 13, 14, 15)  
9                    (3, 4, 8, 9, 10, 12, 13, 14, 15)  
10                (3, 4, 7, 8, 9, 10, 12, 13, 14, 15)  
11            (3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15)  
12         (1, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15)  
13      (1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)  
14   (1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)  
15  (0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14...  
16  (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...

In [60]:
#Recreating the x and y values 
X=edu1.values[:,[3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15]]
Y=edu1.values[:,-1]

In [61]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
#x=scaler.fit_transform(X)
print(X)

[[ 1.08466911 -0.77436363 -0.97937923 ...  0.8819171   0.80239368
   0.81295735]
 [ 1.08466911 -0.77436363 -0.97937923 ...  0.8819171   0.80239368
   0.81295735]
 [ 1.08466911 -0.77436363 -0.97937923 ... -1.13389342 -1.24627103
  -1.23007683]
 ...
 [-0.5734238   0.85053054  1.02105494 ... -1.13389342 -1.24627103
   0.81295735]
 [-0.5734238   0.85053054 -0.97937923 ... -1.13389342 -1.24627103
  -1.23007683]
 [-0.5734238   0.85053054  1.02105494 ... -1.13389342 -1.24627103
  -1.23007683]]


In [62]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [63]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression()
#train the model object
classifier.fit(X_train,Y_train)# fit function is used to train the model

Y_pred=classifier.predict(X_test)

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[15  0  8]
 [ 0 20  3]
 [15  3 32]]
Classification report: 
              precision    recall  f1-score   support

           0       0.50      0.65      0.57        23
           1       0.87      0.87      0.87        23
           2       0.74      0.64      0.69        50

    accuracy                           0.70        96
   macro avg       0.70      0.72      0.71        96
weighted avg       0.72      0.70      0.70        96

Accuracy of the model:  0.6979166666666666


In [65]:
#insight: We can conclude that variance threshold and select k best works well and gives good accuracy and recall 